# Insert keys and tokens for Twitter API
CONSUMER_API_KEY = '___'
CONSUMER_API_SECRET = '___'
ACCESS_TOKEN = '___-___'
ACCESS_TOKEN_SECRET = '___'

#BEARER TOKEN = AAAAAAAAAAAAAAAAAAAAAPw7HAEAAAAAnviJm2k0ibnbDVlSI8MVReyoWis%3DA1wUJSv67UHn15AEcQ7JnuylUwcuDJwKWzDgJW6d4qaYCdaOFh
